TXT_HOW_IT_WORKS_TITLE = 'h2[class="css-zj9thr-howItWorksTitle"]'
INPUT_ADDRESS_FAKE_SEARCH = 'input[id="fake-address-search-input"]'
INPUT_ADDRESS_SEARCH ='input[id="address-search-input-address"]'
TXT_GOOGLE_ADDRESS = 'li[itemid="google-address"]'
TXT_ADDRESS_NOT_FOUND = 'p[class="css-wc4tpc-text"]'
INPUT_ADDRESS_DETAILS_NUMBER = 'input[id="address-details-input-number"]'
RB_COMPLEMENT = 'input[name="withoutComplement"]'
BT_ADDRESS_DETAILS_CONTINUE = 'button[id="address-details-button-continue"]'
