name: Test With Robot Framework

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python
      env:
        PYTHON_VERSION: "3.10.2"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt update
        sudo apt install python3.8
        sudo apt install software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install python"$py_version"

    - name: Verify Python Version
      run: python --version

#    - name: Terraform init
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: terraform init -input=false
#
#    - name: Terraform validation
#      run: terraform validate
#
#    - name: Terraform apply
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: terraform apply -auto-approve -input=false