name: Test With Robot Framework

on: [push]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python
      env:
        PYTHON_VERSION: "3.10"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install python"$py_version"
        sudo apt install -y nodejs

    - name: Verify Python Version
      run: |
          python --version
          nodejs -v
          npm --version

    - name: Install libarys
      run: |
          pip install -U pip
          pip install -r requirements.txt
          python -m Browser.entry init

    - name: Run tests
      run: |
            mkdir results
            robot -d ./results ./TestCase/ValidateBuy.robot

  generate_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports

#      - name: Send report to commit
#        uses: joonvena/robotframework-reporter-action@v2
#        with:
#          gh_access_token: ${{ secrets.GITHUB_TOKEN }}

#    - name: Show results
#      uses: joonvena/robotframework-reporter-action@v2
#      run: |
#           cat /home/runner/work/ChallengeZe/ChallengeZe/results/report.html

#    - name: Terraform init
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: terraform init -input=false
#
#    - name: Terraform validation
#      run: terraform validate
#
#    - name: Terraform apply
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: terraform apply -auto-approve -input=false